In [2]:
import numpy as np
import pandas as pd

data = {
    "Viewer 1": {"Movie 1": 5, "Movie 2": 1, "Movie 3": 4},
    "Viewer 2": {"Movie 1": 4, "Movie 2": 4, "Movie 3": 2},
    "Viewer 3": {"Movie 1": 4, "Movie 2": 3, "Movie 3": 5},
    "Viewer 4": {"Movie 1": 1, "Movie 2": 1, "Movie 3": 5},
    "Viewer 5": {"Movie 1": 3, "Movie 2": 2, "Movie 3": 1}
}

array = np.array([[data[viewer][movie] for movie in data[viewer]] for viewer in data])

In [3]:
array

array([[5, 1, 4],
       [4, 4, 2],
       [4, 3, 5],
       [1, 1, 5],
       [3, 2, 1]])

In [4]:
df = pd.DataFrame(array, columns=data["Viewer 1"], index=data.keys())

In [5]:
df

Movie 1  Movie 2  Movie 3
Viewer 1        5        1        4
Viewer 2        4        4        2
Viewer 3        4        3        5
Viewer 4        1        1        5
Viewer 5        3        2        1

In [6]:
avg_rate = df.mean(axis=0)
avg_rate

Movie 1    3.4
Movie 2    2.2
Movie 3    3.4
dtype: float64

In [7]:
# Viewer Preference: The highest-rated movie by each viewer.

viewer_pref = df.idxmax(axis=1)
viewer_pref

Viewer 1    Movie 1
Viewer 2    Movie 1
Viewer 3    Movie 3
Viewer 4    Movie 3
Viewer 5    Movie 1
dtype: object

In [8]:
# Defining matrices
price_matrix = np.array([[10, 15],
                         [12, 18]])
quantity_matrix = np.array([[30, 40],
                            [25, 35]])

# Multiplying matrices to get total sales
total_sales_matrix = np.dot(price_matrix, quantity_matrix.T)

print("Total Sales Matrix:\n", total_sales_matrix)

Total Sales Matrix:
 [[ 900  775]
 [1080  930]]


In [10]:
data1 = {
    'City 1': [27, 20, 15, 18, 26, 18, 22],
    'City 2': [24, 18, 20, 17, 19, 22, 21],
    'City 3': [23, 23, 27, 25, 16, 21, 22],
    'City 4': [22, 29, 23, 16, 20, 24, 28]
}

In [24]:
df1 = pd.DataFrame(data1)
array1 = np.array(df1)
array1

array([[27, 24, 23, 22],
       [20, 18, 23, 29],
       [15, 20, 27, 23],
       [18, 17, 25, 16],
       [26, 19, 16, 20],
       [18, 22, 21, 24],
       [22, 21, 22, 28]], dtype=int64)

In [12]:
df1

City 1  City 2  City 3  City 4
0      27      24      23      22
1      20      18      23      29
2      15      20      27      23
3      18      17      25      16
4      26      19      16      20
5      18      22      21      24
6      22      21      22      28

In [21]:
avg_temp1 = df1.mean(axis=1)
avg_temp1

0    24.00
1    22.50
2    21.25
3    19.00
4    20.25
5    21.25
6    23.25
dtype: float64