In [2]:
import numpy as np
# Exercise 1 : Array Creation And Manipulation

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array1_1 = np.arange(0,10)
array1_2 = np.linspace(0,9,10, dtype=int)
# print(array1)
# print(array1_1)
array1_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Exercise 2 : Type Conversion And Array Operations
list2 = [3.14, 2.17, 0, 1, 2]
array2 = np.array(list2).astype(int)
array2

array([3, 2, 0, 1, 2])

In [4]:
# Exercise 3 : Working With Multi-Dimensional Arrays
array3 = np.arange(1,10).reshape(3,3)
# array3
array3_3 = np.linspace(1,9,9, dtype=int).reshape(3,3)
array3_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Exercise 4 : Creating Multi-Dimensional Array With Random
array4 = np.random.rand(4,5)
np.set_printoptions(precision=2)
array4

array([[0.26, 0.95, 0.71, 0.25, 0.89],
       [0.75, 0.62, 0.44, 0.15, 0.71],
       [0.63, 0.97, 0.63, 0.98, 0.85],
       [0.29, 0.43, 0.83, 0.79, 0.89]])

In [11]:
# Exercise 5 : Indexing Arrays
array5 = np.arange
array5

ValueError: cannot reshape array of size 15 into shape (3,2)