In [2]:
import numpy as np
# Exercise 1 : Array Creation And Manipulation

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array1_1 = np.arange(0,10)
array1_2 = np.linspace(0,9,10, dtype=int)
# print(array1)
# print(array1_1)
array1_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Exercise 2 : Type Conversion And Array Operations
list2 = [3.14, 2.17, 0, 1, 2]
array2 = np.array(list2).astype(int)
array2

array([3, 2, 0, 1, 2])

In [4]:
# Exercise 3 : Working With Multi-Dimensional Arrays
array3 = np.arange(1,10).reshape(3,3)
# array3
array3_3 = np.linspace(1,9,9, dtype=int).reshape(3,3)
array3_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
# Exercise 4 : Creating Multi-Dimensional Array With Random
array4 = np.random.rand(4,5)
np.set_printoptions(precision=2)
array4

array([[0.31, 0.88, 0.48, 0.77, 0.61],
       [0.98, 0.58, 0.35, 0.55, 0.13],
       [0.39, 0.29, 0.58, 0.46, 0.71],
       [0.81, 0.13, 0.94, 0.12, 0.44]])

In [6]:
# Exercise 5 : Indexing Arrays
array5 = np.arange(15,25,1).reshape(2,5)
array5[1:]

array([[20, 21, 22, 23, 24]])

In [32]:
# Exercise 6 : Reversing Elements
array6 = np.linspace(0,9,10, dtype=int)
array6[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [39]:
# Exercise 7 : Identity Matrix
array7 = np.random.rand(4,4)
np.set_printoptions(precision=0)
array7

array([[1., 1., 0., 1.],
       [0., 0., 0., 1.],
       [1., 0., 0., 1.],
       [0., 1., 1., 0.]])

In [48]:
# Exercise 8 : Simple Aggregate Funcs
array8 = np.arange(0,10,1)
print(f"Sum: {np.sum(array8)}, Average: {np.mean(array8)}")

Sum: 45, Average: 4.5
