In [29]:
import numpy as np
# Exercise 1 : Array Creation And Manipulation

array1 = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array1_1 = np.arange(0,10)
array1_2 = np.linspace(0,9,10, dtype=int)
# print(array1)
# print(array1_1)
array1_2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [28]:
# Exercise 2 : Type Conversion And Array Operations
list2 = [3.14, 2.17, 0, 1, 2]
array2 = np.array(list2).astype(int)
array2

array([3, 2, 0, 1, 2])

In [37]:
# Exercise 3 : Working With Multi-Dimensional Arrays
array3 = np.arange(1,10).reshape(3,3)
# array3
array3_3 = np.linspace(1,9,9, dtype=int).reshape(3,3)
array3_3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
# Exercise 4 : Creating Multi-Dimensional Array With Random
array4 = 